# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31ac4a2d766e383d6af7e4e2f3a9f8877703fe851cc58713c367c277031700bc2dcdab1a1b63b53390ad575f2cf58f6b764c6129ecdd75c68c0405cf876d6cb3

test:
  secret_key_base: 09cf4d3f710a1e1eae36c27eb982ce986466b551c688e06246feba8a08a531779152781f8971e8eb2833e9379268900a45c96a7164869bd105618fcb8b6cfbfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
